// flow-typed signature: 776d203654c733ff252924c678630627
// flow-typed version: <<STUB>>/atom.undo_v^0.5.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom.undo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom.undo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom.undo/dist/atom.undo.cjs' {
  declare module.exports: any;
}

declare module 'atom.undo/dist/atom.undo.es' {
  declare module.exports: any;
}

declare module 'atom.undo/rollup.config' {
  declare module.exports: any;
}

declare module 'atom.undo/src/atom.undo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom.undo/dist/atom.undo.cjs.js' {
  declare module.exports: $Exports<'atom.undo/dist/atom.undo.cjs'>;
}
declare module 'atom.undo/dist/atom.undo.es.js' {
  declare module.exports: $Exports<'atom.undo/dist/atom.undo.es'>;
}
declare module 'atom.undo/rollup.config.js' {
  declare module.exports: $Exports<'atom.undo/rollup.config'>;
}
declare module 'atom.undo/src/atom.undo.js' {
  declare module.exports: $Exports<'atom.undo/src/atom.undo'>;
}
