// flow-typed signature: 63288780b4b4016b1bddff5ecf367b55
// flow-typed version: <<STUB>>/karet.util_v^0.13.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karet.util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karet.util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karet.util/dist/karet.util.cjs' {
  declare module.exports: any;
}

declare module 'karet.util/dist/karet.util.es' {
  declare module.exports: any;
}

declare module 'karet.util/dist/karet.util' {
  declare module.exports: any;
}

declare module 'karet.util/dist/karet.util.min' {
  declare module.exports: any;
}

declare module 'karet.util/rollup.config' {
  declare module.exports: any;
}

declare module 'karet.util/src/karet.util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karet.util/dist/karet.util.cjs.js' {
  declare module.exports: $Exports<'karet.util/dist/karet.util.cjs'>;
}
declare module 'karet.util/dist/karet.util.es.js' {
  declare module.exports: $Exports<'karet.util/dist/karet.util.es'>;
}
declare module 'karet.util/dist/karet.util.js' {
  declare module.exports: $Exports<'karet.util/dist/karet.util'>;
}
declare module 'karet.util/dist/karet.util.min.js' {
  declare module.exports: $Exports<'karet.util/dist/karet.util.min'>;
}
declare module 'karet.util/rollup.config.js' {
  declare module.exports: $Exports<'karet.util/rollup.config'>;
}
declare module 'karet.util/src/karet.util.js' {
  declare module.exports: $Exports<'karet.util/src/karet.util'>;
}
