// flow-typed signature: 0e3dbe6601ae2c2a2fb35fa1ca7af6d3
// flow-typed version: <<STUB>>/kefir.atom_v^5.3.4/flow_v0.53.1

import type { Observable, Property } from 'kefir';

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kefir.atom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kefir.atom' {
  declare type Atom<T, E> =
    Property<T, E> & {
      get: () => T,
      set: (x: T) => void,
      modify: (fn: any) => void,
      view: (lens: any) => Atom<T, E>
    };

  // declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kefir.atom/dist/kefir.atom.cjs' {
  declare module.exports: any;
}

declare module 'kefir.atom/dist/kefir.atom.es' {
  declare module.exports: any;
}

declare module 'kefir.atom/dist/kefir.atom' {
  declare module.exports: any;
}

declare module 'kefir.atom/dist/kefir.atom.min' {
  declare module.exports: any;
}

declare module 'kefir.atom/rollup.config' {
  declare module.exports: any;
}

declare module 'kefir.atom/src/kefir.atom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kefir.atom/dist/kefir.atom.cjs.js' {
  declare module.exports: $Exports<'kefir.atom/dist/kefir.atom.cjs'>;
}
declare module 'kefir.atom/dist/kefir.atom.es.js' {
  declare module.exports: $Exports<'kefir.atom/dist/kefir.atom.es'>;
}
declare module 'kefir.atom/dist/kefir.atom.js' {
  declare module.exports: $Exports<'kefir.atom/dist/kefir.atom'>;
}
declare module 'kefir.atom/dist/kefir.atom.min.js' {
  declare module.exports: $Exports<'kefir.atom/dist/kefir.atom.min'>;
}
declare module 'kefir.atom/rollup.config.js' {
  declare module.exports: $Exports<'kefir.atom/rollup.config'>;
}
declare module 'kefir.atom/src/kefir.atom.js' {
  declare module.exports: $Exports<'kefir.atom/src/kefir.atom'>;
}
