// flow-typed signature: 8ba8bafbdfa28c6afd07469c673df81a
// flow-typed version: <<STUB>>/partial.lenses_v^11.17.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'partial.lenses'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'partial.lenses' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'partial.lenses/dist/partial.lenses.cjs' {
  declare module.exports: any;
}

declare module 'partial.lenses/dist/partial.lenses.es' {
  declare module.exports: any;
}

declare module 'partial.lenses/dist/partial.lenses' {
  declare module.exports: any;
}

declare module 'partial.lenses/dist/partial.lenses.min' {
  declare module.exports: any;
}

declare module 'partial.lenses/rollup.config' {
  declare module.exports: any;
}

declare module 'partial.lenses/src/contract' {
  declare module.exports: any;
}

declare module 'partial.lenses/src/partial.lenses' {
  declare module.exports: any;
}

// Filename aliases
declare module 'partial.lenses/dist/partial.lenses.cjs.js' {
  declare module.exports: $Exports<'partial.lenses/dist/partial.lenses.cjs'>;
}
declare module 'partial.lenses/dist/partial.lenses.es.js' {
  declare module.exports: $Exports<'partial.lenses/dist/partial.lenses.es'>;
}
declare module 'partial.lenses/dist/partial.lenses.js' {
  declare module.exports: $Exports<'partial.lenses/dist/partial.lenses'>;
}
declare module 'partial.lenses/dist/partial.lenses.min.js' {
  declare module.exports: $Exports<'partial.lenses/dist/partial.lenses.min'>;
}
declare module 'partial.lenses/rollup.config.js' {
  declare module.exports: $Exports<'partial.lenses/rollup.config'>;
}
declare module 'partial.lenses/src/contract.js' {
  declare module.exports: $Exports<'partial.lenses/src/contract'>;
}
declare module 'partial.lenses/src/partial.lenses.js' {
  declare module.exports: $Exports<'partial.lenses/src/partial.lenses'>;
}
