// flow-typed signature: f79e16f1469c011d17baf8d427fb4e1e
// flow-typed version: <<STUB>>/yuidocjs_v^0.10.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yuidocjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yuidocjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yuidocjs/conf/docs/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

declare module 'yuidocjs/conf/docs/assets/vendor/prettify/prettify' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/builder' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/cli' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/docparser' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/docview' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/files' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/help' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/index' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/options' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/project' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/server' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/utils' {
  declare module.exports: any;
}

declare module 'yuidocjs/lib/yuidoc' {
  declare module.exports: any;
}

declare module 'yuidocjs/output/api/api' {
  declare module.exports: any;
}

declare module 'yuidocjs/output/api/assets/js/api-filter' {
  declare module.exports: any;
}

declare module 'yuidocjs/output/api/assets/js/api-list' {
  declare module.exports: any;
}

declare module 'yuidocjs/output/api/assets/js/api-search' {
  declare module.exports: any;
}

declare module 'yuidocjs/output/api/assets/js/apidocs' {
  declare module.exports: any;
}

declare module 'yuidocjs/output/api/assets/js/yui-prettify' {
  declare module.exports: any;
}

declare module 'yuidocjs/output/api/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

declare module 'yuidocjs/output/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

declare module 'yuidocjs/output/assets/vendor/prettify/prettify' {
  declare module.exports: any;
}

declare module 'yuidocjs/scripts/report' {
  declare module.exports: any;
}

declare module 'yuidocjs/scripts/versions' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/builder' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/files' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/AreaSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/AreaSplineSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/Axis' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/AxisType' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/BarSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/BottomAxisLayout' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/CartesianChart' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/CartesianChartLegend' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/CartesianSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/CategoryAxis' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/Chart' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/ChartBase' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/ChartLegend' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/CircleGroup' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/ColumnSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/ComboSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/ComboSplineSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/CurveUtil' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/DiamondGroup' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/EllipseGroup' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/Fills' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/Graph' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/Gridlines' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/Histogram' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/LeftAxisLayout' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/Lines' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/LineSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/MarkerSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/NumericAxis' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/PieChart' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/PieChartLegend' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/PieSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/Plots' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/RectGroup' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/Renderer' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/RightAxisLayout' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/ShapeGroup' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/SplineSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedAreaSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedAreaSplineSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedAxis' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedBarSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedColumnSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedComboSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedComboSplineSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedLineSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedMarkerSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackedSplineSeries' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/StackingUtil' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/TimeAxis' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/charts/TopAxisLayout' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/globbing/deep/deep/sub/yui/src/example/example' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/globbing/deep/shallow/yui/src/example/example' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/globbing/shallow/yui/src/example/example' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/inherit/examplemodule' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/json/parse' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/json/stringify' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/namespace/ns' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/preprocessor/preprocessortest' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/test/anim' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/test/test' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/test2/dump/dump' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/test2/namespace' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/test2/oop/oop' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/input/test2/slashes' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/lib/davglass' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/lib/testpreprocessor' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/lib/testpreprocessormodule/testpreprocessormodule' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/options' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/parser_coffee' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/parser' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/preprocessor' {
  declare module.exports: any;
}

declare module 'yuidocjs/tests/utils' {
  declare module.exports: any;
}

declare module 'yuidocjs/themes/default/assets/js/api-filter' {
  declare module.exports: any;
}

declare module 'yuidocjs/themes/default/assets/js/api-list' {
  declare module.exports: any;
}

declare module 'yuidocjs/themes/default/assets/js/api-search' {
  declare module.exports: any;
}

declare module 'yuidocjs/themes/default/assets/js/apidocs' {
  declare module.exports: any;
}

declare module 'yuidocjs/themes/default/assets/js/yui-prettify' {
  declare module.exports: any;
}

declare module 'yuidocjs/themes/default/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

declare module 'yuidocjs/themes/simple/assets/js/tabs' {
  declare module.exports: any;
}

declare module 'yuidocjs/themes/simple/assets/js/yui-prettify' {
  declare module.exports: any;
}

declare module 'yuidocjs/themes/simple/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yuidocjs/conf/docs/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'yuidocjs/conf/docs/assets/vendor/prettify/prettify-min'>;
}
declare module 'yuidocjs/conf/docs/assets/vendor/prettify/prettify.js' {
  declare module.exports: $Exports<'yuidocjs/conf/docs/assets/vendor/prettify/prettify'>;
}
declare module 'yuidocjs/lib/builder.js' {
  declare module.exports: $Exports<'yuidocjs/lib/builder'>;
}
declare module 'yuidocjs/lib/cli.js' {
  declare module.exports: $Exports<'yuidocjs/lib/cli'>;
}
declare module 'yuidocjs/lib/docparser.js' {
  declare module.exports: $Exports<'yuidocjs/lib/docparser'>;
}
declare module 'yuidocjs/lib/docview.js' {
  declare module.exports: $Exports<'yuidocjs/lib/docview'>;
}
declare module 'yuidocjs/lib/files.js' {
  declare module.exports: $Exports<'yuidocjs/lib/files'>;
}
declare module 'yuidocjs/lib/help.js' {
  declare module.exports: $Exports<'yuidocjs/lib/help'>;
}
declare module 'yuidocjs/lib/index.js' {
  declare module.exports: $Exports<'yuidocjs/lib/index'>;
}
declare module 'yuidocjs/lib/options.js' {
  declare module.exports: $Exports<'yuidocjs/lib/options'>;
}
declare module 'yuidocjs/lib/project.js' {
  declare module.exports: $Exports<'yuidocjs/lib/project'>;
}
declare module 'yuidocjs/lib/server.js' {
  declare module.exports: $Exports<'yuidocjs/lib/server'>;
}
declare module 'yuidocjs/lib/utils.js' {
  declare module.exports: $Exports<'yuidocjs/lib/utils'>;
}
declare module 'yuidocjs/lib/yuidoc.js' {
  declare module.exports: $Exports<'yuidocjs/lib/yuidoc'>;
}
declare module 'yuidocjs/output/api/api.js' {
  declare module.exports: $Exports<'yuidocjs/output/api/api'>;
}
declare module 'yuidocjs/output/api/assets/js/api-filter.js' {
  declare module.exports: $Exports<'yuidocjs/output/api/assets/js/api-filter'>;
}
declare module 'yuidocjs/output/api/assets/js/api-list.js' {
  declare module.exports: $Exports<'yuidocjs/output/api/assets/js/api-list'>;
}
declare module 'yuidocjs/output/api/assets/js/api-search.js' {
  declare module.exports: $Exports<'yuidocjs/output/api/assets/js/api-search'>;
}
declare module 'yuidocjs/output/api/assets/js/apidocs.js' {
  declare module.exports: $Exports<'yuidocjs/output/api/assets/js/apidocs'>;
}
declare module 'yuidocjs/output/api/assets/js/yui-prettify.js' {
  declare module.exports: $Exports<'yuidocjs/output/api/assets/js/yui-prettify'>;
}
declare module 'yuidocjs/output/api/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'yuidocjs/output/api/assets/vendor/prettify/prettify-min'>;
}
declare module 'yuidocjs/output/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'yuidocjs/output/assets/vendor/prettify/prettify-min'>;
}
declare module 'yuidocjs/output/assets/vendor/prettify/prettify.js' {
  declare module.exports: $Exports<'yuidocjs/output/assets/vendor/prettify/prettify'>;
}
declare module 'yuidocjs/scripts/report.js' {
  declare module.exports: $Exports<'yuidocjs/scripts/report'>;
}
declare module 'yuidocjs/scripts/versions.js' {
  declare module.exports: $Exports<'yuidocjs/scripts/versions'>;
}
declare module 'yuidocjs/tests/builder.js' {
  declare module.exports: $Exports<'yuidocjs/tests/builder'>;
}
declare module 'yuidocjs/tests/files.js' {
  declare module.exports: $Exports<'yuidocjs/tests/files'>;
}
declare module 'yuidocjs/tests/input/charts/AreaSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/AreaSeries'>;
}
declare module 'yuidocjs/tests/input/charts/AreaSplineSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/AreaSplineSeries'>;
}
declare module 'yuidocjs/tests/input/charts/Axis.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/Axis'>;
}
declare module 'yuidocjs/tests/input/charts/AxisType.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/AxisType'>;
}
declare module 'yuidocjs/tests/input/charts/BarSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/BarSeries'>;
}
declare module 'yuidocjs/tests/input/charts/BottomAxisLayout.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/BottomAxisLayout'>;
}
declare module 'yuidocjs/tests/input/charts/CartesianChart.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/CartesianChart'>;
}
declare module 'yuidocjs/tests/input/charts/CartesianChartLegend.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/CartesianChartLegend'>;
}
declare module 'yuidocjs/tests/input/charts/CartesianSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/CartesianSeries'>;
}
declare module 'yuidocjs/tests/input/charts/CategoryAxis.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/CategoryAxis'>;
}
declare module 'yuidocjs/tests/input/charts/Chart.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/Chart'>;
}
declare module 'yuidocjs/tests/input/charts/ChartBase.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/ChartBase'>;
}
declare module 'yuidocjs/tests/input/charts/ChartLegend.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/ChartLegend'>;
}
declare module 'yuidocjs/tests/input/charts/CircleGroup.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/CircleGroup'>;
}
declare module 'yuidocjs/tests/input/charts/ColumnSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/ColumnSeries'>;
}
declare module 'yuidocjs/tests/input/charts/ComboSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/ComboSeries'>;
}
declare module 'yuidocjs/tests/input/charts/ComboSplineSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/ComboSplineSeries'>;
}
declare module 'yuidocjs/tests/input/charts/CurveUtil.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/CurveUtil'>;
}
declare module 'yuidocjs/tests/input/charts/DiamondGroup.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/DiamondGroup'>;
}
declare module 'yuidocjs/tests/input/charts/EllipseGroup.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/EllipseGroup'>;
}
declare module 'yuidocjs/tests/input/charts/Fills.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/Fills'>;
}
declare module 'yuidocjs/tests/input/charts/Graph.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/Graph'>;
}
declare module 'yuidocjs/tests/input/charts/Gridlines.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/Gridlines'>;
}
declare module 'yuidocjs/tests/input/charts/Histogram.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/Histogram'>;
}
declare module 'yuidocjs/tests/input/charts/LeftAxisLayout.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/LeftAxisLayout'>;
}
declare module 'yuidocjs/tests/input/charts/Lines.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/Lines'>;
}
declare module 'yuidocjs/tests/input/charts/LineSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/LineSeries'>;
}
declare module 'yuidocjs/tests/input/charts/MarkerSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/MarkerSeries'>;
}
declare module 'yuidocjs/tests/input/charts/NumericAxis.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/NumericAxis'>;
}
declare module 'yuidocjs/tests/input/charts/PieChart.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/PieChart'>;
}
declare module 'yuidocjs/tests/input/charts/PieChartLegend.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/PieChartLegend'>;
}
declare module 'yuidocjs/tests/input/charts/PieSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/PieSeries'>;
}
declare module 'yuidocjs/tests/input/charts/Plots.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/Plots'>;
}
declare module 'yuidocjs/tests/input/charts/RectGroup.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/RectGroup'>;
}
declare module 'yuidocjs/tests/input/charts/Renderer.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/Renderer'>;
}
declare module 'yuidocjs/tests/input/charts/RightAxisLayout.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/RightAxisLayout'>;
}
declare module 'yuidocjs/tests/input/charts/ShapeGroup.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/ShapeGroup'>;
}
declare module 'yuidocjs/tests/input/charts/SplineSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/SplineSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackedAreaSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedAreaSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackedAreaSplineSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedAreaSplineSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackedAxis.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedAxis'>;
}
declare module 'yuidocjs/tests/input/charts/StackedBarSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedBarSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackedColumnSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedColumnSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackedComboSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedComboSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackedComboSplineSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedComboSplineSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackedLineSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedLineSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackedMarkerSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedMarkerSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackedSplineSeries.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackedSplineSeries'>;
}
declare module 'yuidocjs/tests/input/charts/StackingUtil.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/StackingUtil'>;
}
declare module 'yuidocjs/tests/input/charts/TimeAxis.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/TimeAxis'>;
}
declare module 'yuidocjs/tests/input/charts/TopAxisLayout.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/charts/TopAxisLayout'>;
}
declare module 'yuidocjs/tests/input/globbing/deep/deep/sub/yui/src/example/example.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/globbing/deep/deep/sub/yui/src/example/example'>;
}
declare module 'yuidocjs/tests/input/globbing/deep/shallow/yui/src/example/example.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/globbing/deep/shallow/yui/src/example/example'>;
}
declare module 'yuidocjs/tests/input/globbing/shallow/yui/src/example/example.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/globbing/shallow/yui/src/example/example'>;
}
declare module 'yuidocjs/tests/input/inherit/examplemodule.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/inherit/examplemodule'>;
}
declare module 'yuidocjs/tests/input/json/parse.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/json/parse'>;
}
declare module 'yuidocjs/tests/input/json/stringify.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/json/stringify'>;
}
declare module 'yuidocjs/tests/input/namespace/ns.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/namespace/ns'>;
}
declare module 'yuidocjs/tests/input/preprocessor/preprocessortest.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/preprocessor/preprocessortest'>;
}
declare module 'yuidocjs/tests/input/test/anim.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/test/anim'>;
}
declare module 'yuidocjs/tests/input/test/test.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/test/test'>;
}
declare module 'yuidocjs/tests/input/test2/dump/dump.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/test2/dump/dump'>;
}
declare module 'yuidocjs/tests/input/test2/namespace.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/test2/namespace'>;
}
declare module 'yuidocjs/tests/input/test2/oop/oop.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/test2/oop/oop'>;
}
declare module 'yuidocjs/tests/input/test2/slashes.js' {
  declare module.exports: $Exports<'yuidocjs/tests/input/test2/slashes'>;
}
declare module 'yuidocjs/tests/lib/davglass.js' {
  declare module.exports: $Exports<'yuidocjs/tests/lib/davglass'>;
}
declare module 'yuidocjs/tests/lib/testpreprocessor.js' {
  declare module.exports: $Exports<'yuidocjs/tests/lib/testpreprocessor'>;
}
declare module 'yuidocjs/tests/lib/testpreprocessormodule/testpreprocessormodule.js' {
  declare module.exports: $Exports<'yuidocjs/tests/lib/testpreprocessormodule/testpreprocessormodule'>;
}
declare module 'yuidocjs/tests/options.js' {
  declare module.exports: $Exports<'yuidocjs/tests/options'>;
}
declare module 'yuidocjs/tests/parser_coffee.js' {
  declare module.exports: $Exports<'yuidocjs/tests/parser_coffee'>;
}
declare module 'yuidocjs/tests/parser.js' {
  declare module.exports: $Exports<'yuidocjs/tests/parser'>;
}
declare module 'yuidocjs/tests/preprocessor.js' {
  declare module.exports: $Exports<'yuidocjs/tests/preprocessor'>;
}
declare module 'yuidocjs/tests/utils.js' {
  declare module.exports: $Exports<'yuidocjs/tests/utils'>;
}
declare module 'yuidocjs/themes/default/assets/js/api-filter.js' {
  declare module.exports: $Exports<'yuidocjs/themes/default/assets/js/api-filter'>;
}
declare module 'yuidocjs/themes/default/assets/js/api-list.js' {
  declare module.exports: $Exports<'yuidocjs/themes/default/assets/js/api-list'>;
}
declare module 'yuidocjs/themes/default/assets/js/api-search.js' {
  declare module.exports: $Exports<'yuidocjs/themes/default/assets/js/api-search'>;
}
declare module 'yuidocjs/themes/default/assets/js/apidocs.js' {
  declare module.exports: $Exports<'yuidocjs/themes/default/assets/js/apidocs'>;
}
declare module 'yuidocjs/themes/default/assets/js/yui-prettify.js' {
  declare module.exports: $Exports<'yuidocjs/themes/default/assets/js/yui-prettify'>;
}
declare module 'yuidocjs/themes/default/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'yuidocjs/themes/default/assets/vendor/prettify/prettify-min'>;
}
declare module 'yuidocjs/themes/simple/assets/js/tabs.js' {
  declare module.exports: $Exports<'yuidocjs/themes/simple/assets/js/tabs'>;
}
declare module 'yuidocjs/themes/simple/assets/js/yui-prettify.js' {
  declare module.exports: $Exports<'yuidocjs/themes/simple/assets/js/yui-prettify'>;
}
declare module 'yuidocjs/themes/simple/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'yuidocjs/themes/simple/assets/vendor/prettify/prettify-min'>;
}
